name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  

jobs:
  terraform:
    name: Terraform Infrastructure Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
      - name: Create and Change Directory
        run: |
          mkdir -p terraform
          cd terraform
          echo "Directory structure:"
          ls -la

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Plan Terraform
        run: |
          terraform plan

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve

  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/time-api:latest .

      - name: Push Docker image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/time-api:latest

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/api-deployment api=gcr.io/${{ secrets.GCP_PROJECT_ID }}/time-api:latest -n example-namespace
          kubectl rollout status deployment/api-deployment -n example-namespace

  verify:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Check API availability
        run: |
          sleep 30 # Wait for the deployment to settle
          curl -f http://35.237.80.226:8080/time || exit 1
