name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  

jobs:
  terraform:
    name: Terraform Infrastructure Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
    #   - name: Create and Change Directory
    #     run: |
    #       mkdir -p /terraform
    #       cp -r./terraform/* /terraform/
    #       cd /terraform
    #       echo "Directory structure:"
    #       ls -la

      - name: Check for Terraform Files
        run: |
          if [ -z "$(ls -A terraform/*.tf 2>/dev/null)" ]; then
          echo "No Terraform files found, skipping."
          exit 0
          fi

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
          
      - name: Plan Terraform
        run: |
          terraform plan
          working_dir: /terraform

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve
          working_dir: /terraform
